version: '3'
services:
  sqlserver:
    restart: unless-stopped
    env_file:
        - .env
    image: "mcr.microsoft.com/mssql/server:latest"
    ports:
      - ${SQL_PORT}:1433
      - 1433
    volumes:
      - "./sql/data:/var/opt/mssql/data"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Developer
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P ${DB_PASSWORD} -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
  sqlserver.configurator:
    image: "mcr.microsoft.com/mssql-tools:latest"
    depends_on:
      sqlserver:
        condition: service_healthy
    command: >
      bash -c "
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P ${DB_PASSWORD} -d master -Q \"IF DB_ID('sys') IS NULL BEGIN CREATE DATABASE [sys]; ALTER DATABASE [sys] SET AUTO_CLOSE OFF; END;\"
      "
  platform_dev:    
    restart: unless-stopped
    env_file:
      - .env
    image: tompitdev/platform:latest-debug
    depends_on:
      sqlserver.configurator:
        condition: service_completed_successfully
    environment:      
    - ASPNETCORE_URLS=http://0.0.0.0:44003;http://0.0.0.0:${DEV_PORT}
    - sys__url=http://127.0.0.1:44003    
    - instanceEndpoints__0__url=http://127.0.0.1:${DEV_PORT}
    - stage=development
    - features=${DEV_FEATURES}
    - storage__databases__defaultConnectionString=data source=sqlserver;initial catalog=sys;user id=sa;password=${DB_PASSWORD};TrustServerCertificate=true;MultipleActiveResultSets=true;
    - settings__0__value=data source=sqlserver;initial catalog=sys;user id=sa;password=${DB_PASSWORD};TrustServerCertificate=true;MultipleActiveResultSets=true;
    - sys__token=${INSTANCE_TOKEN}
    - debugTarget__url=http://platform_qa:44003
    - debugTarget__authenticationToken=${INSTANCE_TOKEN}
    - TP_SHELL_MODE=0
    - Logging__LogLevel__Default=Warning
    - routing__baseUrl=http://127.0.0.1:${DEV_PORT}  
    - settings__1__name=Cors Enabled
    - settings__1__value=true
    - settings__2__name=Cors Origins
    - settings__2__value=http://127.0.0.1:44003,http://127.0.0.1:${DEV_PORT},http://127.0.0.1:${QA_PORT}
    - routing__baseUrl=http://127.0.0.1:${DEV_PORT} 
    - sourceFiles__folder=/microServices/sources
    ports:
      - ${DEV_PORT}:44003
      - 44003
    volumes:
      - ./dev/microServices:/microServices:rw
      - ./dev/packages:/home/tompit/packages:rw
      - ./dev/debugger:/nonexistent:rw
    healthcheck:
      test: ["CMD-SHELL", "nc -vz 127.0.0.1 44003"]
      interval: 10s
      retries: 31
      start_period: 300s
      timeout: 30s
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
  platform_qa:    
    restart: unless-stopped
    env_file:
      - .env
    image: tompitdev/platform:latest-debug
    depends_on:
      sqlserver.configurator:
        condition: service_completed_successfully
      platform_dev:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "nc -vz 127.0.0.1 44003"]
      interval: 5s
      retries: 65
      start_period: 300s
      timeout: 30s
    environment:    
    - ASPNETCORE_URLS=http://0.0.0.0:44003;http://0.0.0.0:${QA_PORT}
    - optimization=debug
    - features=${QA_FEATURES}
    - sys__url=http://platform_dev:44003  
    - instanceEndpoints__0__url=http://127.0.0.1:44003
    - instanceEndpoints__0__name=Internal features
    - instanceEndpoints__0__features=BigData, Search, Worker, Sys
    - instanceEndpoints__1__url=http://127.0.0.1:${QA_PORT}
    - instanceEndpoints__1__name=External features
    - instanceEndpoints__1__features=Application, Development, Management, Cdn, Rest, IoT
    - storage__databases__defaultConnectionString=data source=sqlserver;initial catalog=sys;user id=sa;password=${DB_PASSWORD};TrustServerCertificate=true;MultipleActiveResultSets=true;
    - settings__0__value=data source=sqlserver;initial catalog=sys;user id=sa;password=${DB_PASSWORD};TrustServerCertificate=true;MultipleActiveResultSets=true;
    - sys__token=${INSTANCE_TOKEN}
    - Logging__LogLevel__Default=Warning
    - routing__baseUrl=http://127.0.0.1:${QA_PORT}
    - settings__1__name=Cors Enabled
    - settings__1__value=true
    - settings__2__name=Cors Origins
    - settings__2__value=http://127.0.0.1:44003,http://host.docker.internal:${QA_PORT},http://127.0.0.1:${QA_PORT}
    ports:
      - ${QA_PORT}:44003
      - 44003
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./qa/microServices:/microServices:rw
      - ./qa/packages:/home/tompit/packages:rw
      - ./qa/debugger:/nonexistent:rw
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 2G
